style_profile = {
    "visual_theme": "dark_cinematic",
    "font": "Montserrat-Bold",
    "caption_color": "#FFD700",
    "caption_outline_color": "#000000",
    "caption_font_size": 48,
    "caption_position": "bottom_center",
    "music_genre": "Lo-fi Suspense",
    "color_filter": "vignette,eq=contrast=1.2:brightness=0.95:saturation=1.1",
    "overlay_opacity": 0.35,
    "video_resolution": "1080x1920",
    "video_fps": 30,
    "video_aspect_ratio": "9:16",
    "watermark_text": "",
    "watermark_color": "#FFFFFF",
    "watermark_opacity": 0.7,
    "watermark_position": "top_right",
    "intro_duration_sec": 3,
    "hook_duration_sec": 5,
    "transition_style": "fade",
    "transition_duration_ms": 300,
    "script_tone": "viral_suspenseful",
    "script_hook_style": "open_loop",
    "script_cta_style": "subscribe_comment",
    "output_format": "mp4",
    "output_quality": "high",
    "srt_word_gap_ms": 200,
    "telegram_preview_label": "[PREVIEW]",
    "telegram_raw_label": "[RAW FILES]",
}
